//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorTbl
    {
        public int AutId { get; set; }
        public string AutName { get; set; }
        public string AutGender { get; set; }
        public string AutCountry { get; set; }
    }
}
